#!/usr/bin/env zsh

. /opt/dowse/env
. ${dowse_daemons_conf}/dns-leases

dnscrypt_name="ipredator"

DOWSE_DOMAINLIST=${dowse_install_dir}/domain-list/data \
		DOWSE_LAN_ADDRESS_IP4=$address \
		DOWSE_LAN_NETMASK_IP4=$netmask \
		hostname=$hostname \
		domain=$lan \
		interface=$interface \
		dnscrypt-proxy -a $address:53 \
		-l ${dowse_logdir}/dnscrypt.log \
		-L ${dowse_install_dir}/dnscrypt-resolvers.csv \
		-R "${dnscrypt_name}" \
		-X ${dowse_install_dir}/src/dnscrypt-plugin/dnscrypt_dowse.so${args} \
		-d -m 7 -u ${dowse_uid}

