#!/bin/zsh

. /opt/dowse/env
. ${dowse_daemons_conf}/mysqld

mkdir -p ${dowse_working_dir}/data/mysql
mkdir -p ${dowse_livedir}/mysql
[[ -r ${dowse_working_dir}/data/mysql/ibdata1 ]] || {
	notice "Initialisation of MySQL databases"
	${dowse_install_dir}/mysql/bin/mysql_install_db --user=$dowse_uid \
								  --force \
								  --basedir=${dowse_install_dir}/mysql \
								  --datadir=${dowse_working_dir}/data/mysql

}
mysqld --defaults-file="${daemons_conf}/mysqld" &!

sql_set_root_password 'p4ssw0rd' ${dowse_working_dir}/data/mysqld.setted_password

# make sure the current database exists
sql_create_database things

# cut used to parse out what follows semicolon
cut -d\; -f1 $thingidx |
           sql_create_table found | $sql $db[things] 2>/dev/null

cut -d\; -f1 $eventidx |
    sql_create_table event | $sql $db[things] 2>/dev/null
cut -d\; -f1 $parameteridx |
    sql_create_table parameter | $sql $db[things] 2>/dev/null
act "Adding DB constraint"
cat $constraintidx | $sql $db[things] 2>/dev/null
act "Populate the parameter table"
echo "INSERT IGNORE INTO parameter(variable,value) VALUES ('state all things','ON') " | $sql $db[things] 2>/dev/null
echo "INSERT IGNORE INTO parameter(variable,value) VALUES ('party mode','OFF') " | $sql $db[things] 2>/dev/null
# create trigger and redis function
sql_integrate_with_redis ${dowse_working_dir}/data/mysqld.integrated_redis
