#!/bin/sh
#
# Copyright (C) 2017 Dyne.org Foundation
#
# Dowse is designed, written and maintained by Denis Roio <jaromil@dyne.org>
#
# This source code is free software; you can redistribute it
# and/or modify it under the terms of the GNU Public License
# as published by the Free Software Foundation; either
# version 3 of the License, or (at your option) any later
# version.
#
# This source code is distributed in the hope that it will be
# useful, but WITHOUT ANY WARRANTY; without even the implied
# warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
# PURPOSE.  Please refer to the GNU Public License for more
# details.
#
# You should have received a copy of the GNU Public License
# along with this source code; if not, write to: Free
# Software Foundation, Inc., 675 Mass Ave, Cambridge, MA
# 02139, USA.

. /opt/dowse/env
. $dowse_daemons_conf/node-red

nodereddir=$dowse_livedir/node-red/nodes

if [ ! -d $nodereddir ]; then
	mkdir -p $nodereddir
fi

NODE_PATH="$dowse_install_dir/src/node_modules" \
		$dowse_install_dir/src/node_modules/node-red/bin/node-red-pi \
		-s $dowse_generated_conf/node-red.conf
