#!/usr/bin/env zsh

# also see:
# $R/run/pgl/lib/pgl/pglcmd.defaults
# $R/run/pgl/lib/pgl/pglcmd.main

# NOT WORKING
#$R/bin/sup $R/bin/pglcmd start

. /opt/dowse/env
. conf/pglcmd

while 1 ; do sleep 60 ; done

