#!/bin/sh

. /opt/dowse/env
. ${dowse_daemons_conf}/redis

redis-server ${dowse_generated_conf}/redis $*

# we consider these to tell us if it's the initial startup of redis
# yes, redis returns 1 if a key is found
print "exists state_all_things" | redis storage && {
	print "set state_all_things on" | redis storage
}

print "exists party_mode" | redis storage && {
	print "set party_mode off" | redis storage
}

