#!/bin/sh

. /opt/dowse/env

hostname=$hostname \
		domain=$lan \
		address=$address \
		interface=$interface \
		exec python3 $dowse_install_dir/src/webui2/webui.py \
		-p ${dowse_livedir}/webui2.pid

