#!/bin/sh

cat <<EOF > ${dowse_generated_conf}/dnsmasq.conf
# Use default port
port=53

# Never forward plain names (without a dot or domain part)
domain-needed
# Never forward addresses in the non-routed address spaces.
bogus-priv

# Do not read /etc/resolv.conf, use instead stubby as server
no-resolv

# Point the server to the local stubby interface
server=::1#53000
server=127.0.0.1#53000

# Run as dowse user:group
user=${dowse_uid}
group=${dowse_gid}

no-dhcp-interface=

# For debugging purposes, log each DNS query as it passes through
# dnsmasq.
#log-queries

# Increase cache size
cache-size=1000

EOF

if [ ! -z $internet_interface ]; then
	cat <<EOF >> $dowse_generated_conf/dnsmasq.conf
# Listen on the dowse internet interface
interface=${internet_interface}

EOF
fi

