#!/bin/zsh

source /opt/dowse/env

cat << EOF > ${daemons_conf}/mysqld
[client]
port		= 63306
socket		= ${dowse_livedir}/mysql/mysqld.sock
#socket		= /tmp/mysqld.sock

[mysqld]
user		= $dowse_uid
plugin_dir      = /usr/local/dowse/mysql/plugin
pid-file	= ${dowse_livedir}/mysqld.pid
socket		= ${dowse_livedir}/mysqld.sock
#socket		= /tmp/mysqld.sock
port		= 63306
basedir		= ${dowse_install_dir}/mysql
datadir		= ${dowse_working_dir}/data/mysql
tmpdir		= /tmp
lc-messages-dir	= ${dowse_install_dir}/mysql/share
skip-external-locking
bind-address		= 127.0.0.1
#======================================
# /etc/my.cnf:
innodb_buffer_pool_size=5M
innodb_log_buffer_size=256K

query_cache_size=0
max_connections=5
key_buffer_size=8
thread_cache_size=0
host_cache_size=0
innodb_ft_cache_size=1600000
innodb_ft_total_cache_size=32000000

# per thread or per operation settings
thread_stack=131072
sort_buffer_size=32K
read_buffer_size=8200
read_rnd_buffer_size=8200
max_heap_table_size=16K
tmp_table_size=1K
bulk_insert_buffer_size=0
join_buffer_size=128
net_buffer_length=1K
innodb_sort_buffer_size=64K

#settings that relate to the binary log (if enabled)
binlog_cache_size=4K
binlog_stmt_cache_size=4K
#======================================

key_buffer		= 16M
max_allowed_packet	= 16M
thread_stack		= 192K
thread_cache_size       = 8

myisam-recover         = BACKUP
#max_connections        = 100
#table_cache            = 64
#thread_concurrency     = 10

query_cache_limit	= 1M
query_cache_size        = 4M

# Be aware that this log type is a performance killer.
# As of 5.1 you can enable the log at runtime!
general_log_file        = ${dowse_log}/general_mysql.log
general_log             = 1

# Error log - should be very few entries.
log_error = ${dowse_log}/mysql_error.log

# Here you can see queries with especially long duration
slow_query_log_file = ${dowse_log}/mysql-slow.log
slow_query_log      = 1
long_query_time = 1
log_queries_not_using_indexes

# The following can be used as easy to replay backup logs or for replication.
# note: if you are setting up a replication slave, see README.Debian about
#       other settings you may need to change.
#server-id		= 1
#log_bin			= /var/log/mysql/mysql-bin.log
expire_logs_days	= 10
max_binlog_size     = 100M
#binlog_do_db		= include_database_name
#binlog_ignore_db	= include_database_name

# InnoDB is enabled by default with a 10MB datafile in /var/lib/mysql/.
# Read the manual for more InnoDB related options. There are many!
#
# * Security Features
#
# Read the manual, too, if you want chroot!
# chroot = /var/lib/mysql/

[mysqldump]
quick
quote-names
max_allowed_packet	= 16M

[mysql]
# faster start of mysql but no tab completition
no-auto-rehash

[isamchk]
key_buffer		= 16M


# to reduce CPU consumption
skip_name_resolve = ON

# only to eliminate false warning
innodb_log_file_size=1048576
innodb_buffer_pool_instances=1

EOF
