#!/bin/sh

# also see:
# $R/run/pgl/lib/pgl/pglcmd.defaults
# $R/run/pgl/lib/pgl/pglcmd.main

cat <<EOF > ${daemons_conf}/pglcmd
LOCAL_BLOCKLIST_DIR="${dowse_install_dir}/conf/blocklists"
BLOCKLISTS_LIST=""
ALLOW_IN="$H/conf/whitelist.p2p"
ALLOW_OUT="$H/conf/whitelist.p2p"
LOGDIR="$H/log"
DAEMON_LOG="\${LOGDIR}/pgld.log"
WD="0"
EOF
